Algoritmo "areacirculo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
//
// Descrição   : Calcular a área do circulo
// Autor(a)    : Ana Clara Farias
// Data atual  : 03/09/2024
Var
// Seção de Declarações das variáveis
raio: real
area: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Escreva o valor do raio:")
leia (raio)

area <- pi *raio *raio
escreval ("o valor da area é: ",area:2:2)


Fimalgoritmo