Algoritmo "ExercicioL05F"
// Disciplina   : Lógica de Programação com JS
// Professor   : Jailson Obama
// Descrição   : Apresentar todos os números divisíveis por 4 que sejam menores que 200.
// Autor(a)    : Ana Bertochi
// Data atual  : 26/09/2024
Var
   i: inteiro
Inicio
   Para i de 1 ate 199 faca
      Se (i % 4 = 0) Entao
         EscrevaL(i)
      Fimse
   Fimpara
Fimalgoritmo