Algoritmo "ExercicioL05E"
// Disciplina   : Lógica de Programação com JS
// Professor   : Jailson Obama
// Descrição   : Apresentar todos os valores numéricos inteiros ímpares situados na faixa de 0 a 20.
// Autor(a)    : Ana Bertochi
// Data atual  : 26/09/2024
Var
   i: inteiro
Inicio
   Para i de 0 ate 20 faca
      Se (i % 2 = 1) Entao
         EscrevaL(i)
      Fimse
   Fimpara
Fimalgoritmo